## EXP:1.Implement and demonstrate depth first search algorithm and water jug problem

In [2]:
class WaterJugProblem:
    def __init__(self,jug1_capacity,jug2_capacity,target):
        self.jug1_capacity=jug1_capacity
        self.jug2_capacity=jug2_capacity
        self.target=target
        self.visited=set()
    def dfs(self,jug1,jug2):
        if(jug1,jug2) in self.visited:
            return False
        self.visited.add((jug1,jug2))
        if jug1==self.target or jug2==self.target:
            print("Target reached")
            return True
        operations=[(self.jug1_capacity,jug2),(jug1,self.jug2_capacity),(0,jug2),(jug1,0),
                   (min(jug1+jug2,self.jug1_capacity),jug2-(min(jug1+jug2,self.jug1_capacity)-jug1)),
                   (jug1-(min(jug1+jug2,self.jug2_capacity)-jug2),min(jug1+jug2,self.jug2_capacity))]
        for operation in operations:
            if self.dfs(*operation):
                print("operation :",operation)
                return True
        return False
def main():
    jug1_capacity=4
    jug2_capacity=3
    target=2
    water_jug_problem=WaterJugProblem(jug1_capacity,jug2_capacity,target)
    if not water_jug_problem.dfs(0,0):
        print("Target cannot be reached !")
if __name__=="__main__":
    main()

        

Target reached
operation : (4, 2)
operation : (3, 3)
operation : (3, 0)
operation : (0, 3)
operation : (4, 3)
operation : (4, 0)


## EXP 5:N-Queens Problem

In [4]:
print("Enter the number of queens:");
N=int(input())
board=[[0]*N for _ in range(N)]
def is_safe(row,col):
    for i in range(row):
        if board[i][col]==1:
            return False
    for i,j in zip(range(row,-1,-1),range(col,-1,-1)):
        if board[i][j]==1:
            return False
    for i,j in zip(range(row,-1,-1),range(col,N)):
        if board[i][j]==1:
            return False
    return True
def solve(row):
    if row>=N:
        return True
    for col in range(N):
        if is_safe(row,col):
            board[row][col]=1
            if solve(row+1):
                return True
            board[row][col]=0
    return False
solve(0)
for row in board:
    print(row)

Enter the number of queens:
8
[1, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 1, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 1]
[0, 0, 0, 0, 0, 1, 0, 0]
[0, 0, 1, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 1, 0]
[0, 1, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 0, 0, 0]


## EXP:6.Implementation of TSP using Heuristic approach

In [11]:
from sys import maxsize
from itertools import permutations
V=4

def travellingSalesmanProblem(graph,s):
    vertex=[]
    for i in range(V):
        if i!=s:
            vertex.append(i)
            
    min_path=maxsize
    next_permutation=permutations(vertex)
    for i in next_permutation:
        current_pathweight=0
            
        k=s
        for j in i:
            current_pathweight+=graph[k][j]
            k=j
        current_pathweight+=graph[k][s]
                
        min_path=min(min_path,current_pathweight)
    return min_path
if __name__ =="__main__":
    graph=[[0,10,15,20],[10,0,35,25],[15,35,0,30],[20,25,30,0]]
    s=0
    print(travellingSalesmanProblem(graph,s))

80


## Exp:7.Problem solving strategy using forward or backward chaining

In [16]:
initial_state=["fresh"]
rules=[{"if":["clean","smelly"],"then":["fresh"]},{"if":["dirty"],"then":["clean"]}]
goal=["dirty","smelly"]
current_state=initial_state

while not all(x in current_state for x in goal):
    if all(x in current_state for x in goal):
        break
    for rule in reversed(rules):
         if all(x in current_state for x in rule ["then"]):
                current_state+=rule["if"]
print("The final state is:",current_state)                                                                          
                                                                         

The final state is: ['fresh', 'clean', 'smelly', 'dirty', 'clean', 'smelly']


In [18]:
initial_state=["dirty","smelly"]
rules=[{"if":["dirty"],"then":["clean"]},{"if":["clean","smelly"],"then":["fresh"]}]
goal=["fresh"]
current_state=initial_state

while not all(x in current_state for x in goal):
    
    for rule in rules:
         if all(x in current_state for x in rule ["if"]):
                current_state+=rule["then"]
print("The final state is:",current_state)                                                                          
                                                           

The final state is: ['dirty', 'smelly', 'clean', 'fresh']


## Exp 3:A* problem

In [5]:
def aStarAlgo(start_node,stop_node):
    open_set=set([start_node])
    closed_set=set()
    g={start_node:0}
    parents={start_node:start_node}
    
    while open_set:
        n=None
        
        for v in open_set:
            if n is None or g[v]+heuristic(v)<g[n]+heuristic(n):
                n=v
                
        if n is None:
            print("Path does not exists!")
            return None
        if n==stop_node:
            path=[]
            while parents[n]!=n:
                path.append(n)
                n=parents[n]
            path.append(start_node)
            path.reverse()
            print(f"Path found:{path}")
            return path
        
        open_set.remove(n)
        closed_set.add(n)
        
        for (m,weight) in get_neighbors(n):
            if m in closed_set:
                continue
                
            tentative_g=g[n]+weight
            
            if m  not in open_set or tentative_g<g[m]:
                g[m]=tentative_g
                parents[m]=n
                open_set.add(m)
    print("Path does not exists!")
    return None

def get_neighbors(v):
    return Graph_nodes.get(v,[])

def heuristic(n):
    H_dist={'A':10,'B':8,'C':5,'D':7,'E':3,'F':6,'G':5,'H':3,'I':1,'J':0}
    return H_dist[n]

Graph_nodes={
    'A':[('B',6),('F',3)],
    'B':[('C',3),('D',2)],
    'C':[('E',5),('D',1)],
    'D':[('E',8)],
    'E':[('I',5),('J',5)],
    'F':[('G',1),('H',7)],
    'G':[('I',3)],
    'H':[('F',7),('I',2)],
    'I':[('J',3)]
}

aStarAlgo('A','J')

Path found:['A', 'F', 'G', 'I', 'J']


['A', 'F', 'G', 'I', 'J']

## EXP 9: Tic-Tac-Toe

In [8]:
import os
import time
board=[' ',' ',' ',' ',' ',' ',' ',' ',' ',' ']
player=1

win=1
Draw=-1
running=0
stop=1

Game=running
mark='X'

def DrawBoard():
    print(" %c| %c| %c "%(board[1],board[2],board[3]))
    print("__|__|__")
    print(" %c| %c| %c "%(board[4],board[5],board[6]))
    print("__|__|__")
    print(" %c| %c| %c "%(board[7],board[8],board[9]))
    print("  |  |  ")
    
def checkposition(x):
    if(board[x]==' '):
        return True
    else:
        return False
    
def checkwin():
    global Game
    if(board[1]==board[2] and board[2]==board[3] and board[1]!=' '):
        Game=win
    elif(board[4]==board[5] and board[5]==board[6] and board[4]!=' '):
        Game=win
    elif(board[7]==board[8] and board[8]==board[9] and board[7]!=' '):
        Game=win
        
    elif(board[1]==board[4] and board[4]==board[7] and board[1]!=' '):
        Game=win
    elif(board[2]==board[5] and board[5]==board[8] and board[2]!=' '):
        Game=win
    elif(board[3]==board[6] and board[6]==board[9] and board[3]!=' '):
        Game=win
        
    elif(board[1]==board[5] and board[5]==board[9] and board[5]!=' '):
        Game=win
    elif(board[3]==board[5] and board[5]==board[7] and board[5]!=' '):
        Game=win
        
        
    elif(board[1]!=' ' and board[2]!=' ' and board[3]!=' ' and board[4]!=' ' and board[5]!=' ' and board[6]!=' ' and board[7]!=' ' and board[8]!=' ' and board[0]!=' '):
        Game=Draw
    else:
        Game=running
print("Player 1 [X]--Player 2 [O]\n")
print()
print()
print("Please wait..")
time.sleep(3)
while(Game==running):
    os.system('clear')
    DrawBoard()
    if(player %2!=0):
        print("Player 1's chance")
        Mark='X'
    else:
        print("Player 2's chance")
        Mark='O'
    choice=int(input("Enter the position between [1-9] where you want to mark:"))
    if(checkposition(choice)):
        board[choice]=Mark
        player+=1
        checkwin()
os.system('clear')
DrawBoard()
if(Game==Draw):
    print("Game Draw")
elif(Game==win):
    player-=1
    if(player % 2!=0):
        print("Player 1 won")
    else:
        print("Player 2 won")

    
        
    
    
   



Player 1 [X]--Player 2 [O]



Please wait..
  |  |   
__|__|__
  |  |   
__|__|__
  |  |   
  |  |  
Player 1's chance
Enter the position between [1-9] where you want to mark:1
 X|  |   
__|__|__
  |  |   
__|__|__
  |  |   
  |  |  
Player 2's chance
Enter the position between [1-9] where you want to mark:2
 X| O|   
__|__|__
  |  |   
__|__|__
  |  |   
  |  |  
Player 1's chance
Enter the position between [1-9] where you want to mark:4
 X| O|   
__|__|__
 X|  |   
__|__|__
  |  |   
  |  |  
Player 2's chance
Enter the position between [1-9] where you want to mark:6
 X| O|   
__|__|__
 X|  | O 
__|__|__
  |  |   
  |  |  
Player 1's chance
Enter the position between [1-9] where you want to mark:7
 X| O|   
__|__|__
 X|  | O 
__|__|__
 X|  |   
  |  |  
Player 1 won


## Exp :Chatbot

In [11]:
print("Simple questioning and answering program")
print("-------------------")
print("You may ask any one of these question")
print("Hi")
print("How are you")
print("Are you studying")
print("What is your name")
print("What did you do yesterday")
print("Quit")
while True:
    question=input("Enter one question from above list")
    question=question.lower()
    if question in ['hi']:
        print("Hello")
    elif question in ['how are you','how do you do']:
        print("I am fine")
    elif question in ['are you studying','are you doing any job']:
        print("Yes.I am studying in VCET puttur")
    elif question in ['what is your name']:
        print("My name is Dhanya")
        name=input("Enter your name")
        print("Nice name")
    elif question in ['what did you do yesterday']:
        print("I saw a film")
    elif question in ['quit']:
        break
    else:
        print("I dont understand")
    
    

Simple questioning and answering program
-------------------
You may ask any one of these question
Hi
How are you
Are you studying
What is your name
What did you do yesterday
Quit
Enter one question from above listhow are you
I dont understand
Enter one question from above listhi
Hello
Enter one question from above listquit


## exp:5

In [2]:
def negate_literal(literal):
    return literal[1:] if literal.startswith('~') else '~' + literal
def resolve(clause1,clause2):
    new_clause=[]
    resolved=False
    
    for literal in clause1:
        if negate_literal(literal) in clause2:
            resloved=True
        else:
            new_clause.append(literal)
    
    for literal in clause2:
        if negate_literal(literal)  not in clause1:
            new_clause.append(literal)
    
    return new_clause if resolved else None
def resolution(propositional_kb,query):
    kb=[list(clause) for clause in propositional_kb]
    kb.append([negate_literal(query)])
    
    while True:
        new_clauses=[]
        n=len(kb)
        resolved_pairs=set()
        
        for i in range(n):
            for j in range(i+1,n):
                clause1=kb[i]
                clause2=kb[j]
                pair=(tuple(clause1),tuple(clause2))
                      
                if pair not in resolved_pairs:
                      resolved_pairs.add(pair)
                      resolvent=resolve(clause1,clause2)
                      
                        if resolvent is None:
                             continue
                        if len(resolvent)==0:
                              return True
                     
                        if tuple(resolvent) not in [tuple(c) for c in kb+new_clauses]:
                              new_clauses.append(resolvent)
        if not new_clauses:
            return False
        kb.extend(new_clauses)
if __name__=="__main__":
        propositional_kb=[
            ['B11','~P12'],
            ['B11','~P21'],
            ['~B11']
        ]
        query='~p12'
        result = resolution(propositional_kb,query)
                      
        if result:
                print(f"The query '{query}' is proved")
        else:
                print(f"The query '{query}' is disproved")

The query '~p12' is disproved


## Exp no.9

In [4]:
import numpy as np

ROW_COUNT=6; COLUMN_COUNT=7

def create_board():
    return np.zeros((ROW_COUNT,COLUMN_COUNT),dtype=int)
 
def drop_piece(board,row,col,piece):
    board[row][col]=piece
    
def is_valid_location(board,col):
    return board[ROW_COUNT-1][col]==0
def get_next_open_row(board,col):
    board[row][col]=piece
    
def is_valid_location(board,col):
    return board[ROW_COUNT-1][col]==0
def get_next_open_row(board,col):
    for r in range(ROW_COUNT):
        if board[r][col]==0:
            return r

def winning_move(board,piece):
    for c in range(COLUMN_COUNT-3):
        for r in range(ROW_COUNT):
            if board[r][c]==piece and \
               board[r][c+1]==piece and \
               board[r][c+2]==piece and \
               board[r][c+3]==piece :
                 return True
            
    for c in range(COLUMN_COUNT):
        for r in range(ROW_COUNT-3):
            if board[r][c]==piece and \
               board[r+1][c]==piece and \
               board[r+2][c]==piece and \
               board[r+3][c]==piece :
                 return True
            
    for c in range(COLUMN_COUNT-3):
        for r in range(ROW_COUNT-3):
            if board[r][c]==piece and \
               board[r+1][c+1]==piece and \
               board[r+2][c+2]==piece and \
               board[r+3][c+3]==piece :
                 return True
            
    for c in range(COLUMN_COUNT-3):
        for r in range(3,ROW_COUNT):
            if board[r][c]==piece and \
               board[r-1][c+1]==piece and \
               board[r-2][c+2]==piece and \
               board[r-3][c+3]==piece :
                 return True
    return False
def print_board(board):
    print(np.flip(board,0))
def play_game():
    board=create_board()
    print_board(board)
    game_over=False
    turn=0
    while not game_over:
        if turn==0:
            col=int(input("Player 1,choose a column(0-6):"))
            if is_valid_location(board,col):
                row=get_next_open_row(board,col)
                drop_piece(board,row,col,1)
            if winning_move(board,1):
                print("Player 1 wins!")
                game_over=True
        else:
            col=int(input("Player 2,choose a column(0-6):"))
            if is_valid_location(board,col):
                row=get_next_open_row(board,col)
                drop_piece(board,row,col,2)
            if winning_move(board,2):
                print("Player 2 wins!")
                game_over=True
        print_board(board)
        turn+=1
        turn%=2
        if np.all(board!=0):
            print("Its a tie!")
            game_over=True
            
if __name__=="__main__":
    play_game()
            

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
Player 1,choose a column(0-6):3
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]]
Player 2,choose a column(0-6):3
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0]
 [0 0 0 1 0 0 0]]
Player 1,choose a column(0-6):4
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0]
 [0 0 0 1 1 0 0]]
Player 2,choose a column(0-6):1
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0]
 [0 2 0 1 1 0 0]]
Player 1,choose a column(0-6):5
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 2 0 0 0]
 [0 2 0 1 1 1 0]]
Player 2,choose a column(0-6):4
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 2 2 0 0]
 [0 2 0 1 1 1 0]]
Player 1,choose a column(0-6):6
Player 1 wins!
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 

## Exp 11:

In [3]:
from queue import PriorityQueue
rules={'L1':(2,0),'L2':(1,1),'L3':(0,2),'L4':(1,0),'L5':(0,1),
      'R1':(2,0),'R2':(1,1),'R3':(0,2),'R4':(1,0),'R5':(0,1)
}
def heuristic(state):
    ml,cl,b=state
    return ml+cl
def is_valid(ml,cl,mr,cr):
    return(0<=ml<=3 and 0<=cl<=3 and 0<=mr<=3 and 0<=cr<=3 and 
          (ml==0 or ml>cl) and (mr==0 or mr>cr))
def get_successors(state):
    ml,cl,b=state
    successors=[]
    for rule,(dm,dc) in rules.items():
        if b==1 and rule.startswith('L'):
            nml,ncl=ml-dm,cl-dc
            nmr,ncr=3-nml,3-ncl
            if is_valid(nml,ncl,nmr,ncr):
                successors.append(((nml,ncl,0),rule))
        elif b==0 and rule.startswith('R'):
            nml,ncl=ml+dm,cl+dc
            nmr,ncr=3-nml,3-ncl
            if is_valid(nml,ncl,nmr,ncr):
                successors.append(((nml,ncl,1),rule))
    return successors
def best_first_search(start,goal,target_path=None):
    visited=set()
    pq=PriorityQueue()
    pq.put((heuristic(start),start,[]))
    while not pq.empty():
        _,current,path=pq.get()
        if current in visited:
            continue
        visited.add(current)
        if current==goal:
            return[("Start",start)]+path
        for succ,rule in get_successors(current):
            if succ not in visited:
                new_path=path+[(rule,succ)]
                if target_path:
                    priority=len(target_path)-sum(1 for i,(r,_) in enumerate(new_path) if i<len(target_path) and r==target_path[i])
                else:
                    priority=heuristic(succ)
                pq.put((priority,succ,new_path))
    return None
target_rule_path=['L2','R4','L3','R5','L1','R2','L1','R5','L3','R5','L3']
start_state=(3,3,1)
goal_state=(0,0,0)
solution=best_first_search(start_state,goal_state,target_rule_path)
print("Step | Rule | Left Bank | Right Bank")
print("-----|------|-----------|-------------")
for i,(rule,state) in enumerate(solution):
    ml,cl,b=state
    mr,cr=3-ml,3-cl
    br=1-b
    print(f"{i:>4} | {rule:>4} | [{ml}M, {cl}C, {b}B]   |[{mr}M, {cr}C, {br}B]")
            

Step | Rule | Left Bank | Right Bank
-----|------|-----------|-------------


TypeError: 'NoneType' object is not iterable